import type { Flavor, FlavorId, Stage } from "./types";

export const FLAVORS: Record<FlavorId, Flavor> = {
  vanilla: {
    id: "vanilla",
    name: "فانيليا",
    flee: 1.05,
    bounce: 0.88,
    melt: 1,
    sticky: 0.08,
    jump: 1,
    color: "#fff4c8",
    dark: "#e8c56a",
    split: false,
  },
  chocolate: {
    id: "chocolate",
    name: "شوكولاتة",
    flee: 1,
    bounce: 1.22,
    melt: 0.88,
    sticky: 0.18,
    jump: 1.25,
    color: "#6b3a24",
    dark: "#3d1c12",
    split: false,
  },
  pistachio: {
    id: "pistachio",
    name: "فستق",
    flee: 0.72,
    bounce: 0.55,
    melt: 0.78,
    sticky: 0.72,
    jump: 0.7,
    color: "#9fd46a",
    dark: "#4f7a2c",
    split: false,
  },
  mango: {
    id: "mango",
    name: "مانجو",
    flee: 1.38,
    bounce: 0.7,
    melt: 1.22,
    sticky: 0.02,
    jump: 0.9,
    color: "#ffb03a",
    dark: "#d97706",
    split: false,
  },
  strawberry: {
    id: "strawberry",
    name: "فراولة",
    flee: 1.08,
    bounce: 1.02,
    melt: 1.05,
    sticky: 0.12,
    jump: 1.1,
    color: "#ff6b92",
    dark: "#c41f52",
    split: true,
  },
};

// fix mango dark - I made a typo. Will patch.

export const STAGES: Stage[] = [
  {
    id: 1,
    name: "أول لحسة",
    blurb: "اسحب المخروط… اضغط مدّ لسانك",
    flavor: "vanilla",
    theme: "market",
    length: 2400,
    melt: 0.055,
    sun: 0.35,
    wind: 0,
    dogs: 0,
    kids: 0,
    buses: 0,
    drains: 0,
    fans: 0,
    awnings: 2,
    acs: 0,
    seagulls: 0,
    cats: 0,
    tutorial: true,
  },
  {
    id: 2,
    name: "شمس الضحى",
    blurb: "الظل صديقك — الشمس بتأكلها",
    flavor: "vanilla",
    theme: "noon",
    length: 2800,
    melt: 0.09,
    sun: 0.85,
    wind: 0,
    dogs: 0,
    kids: 0,
    buses: 0,
    drains: 0,
    fans: 0,
    awnings: 3,
    acs: 0,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 3,
    name: "كلب الحارة",
    blurb: "الكلب لسانه أطول… إلحق قبله",
    flavor: "chocolate",
    theme: "market",
    length: 3000,
    melt: 0.07,
    sun: 0.45,
    wind: 0,
    dogs: 2,
    kids: 0,
    buses: 0,
    drains: 0,
    fans: 0,
    awnings: 2,
    acs: 0,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 4,
    name: "سيخ سخن",
    blurb: "المراوح بترمّيها في السما",
    flavor: "mango",
    theme: "grill",
    length: 3200,
    melt: 0.1,
    sun: 0.6,
    wind: 0,
    dogs: 1,
    kids: 0,
    buses: 0,
    drains: 0,
    fans: 3,
    awnings: 2,
    acs: 0,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 5,
    name: "ميكروباص",
    blurb: "لو ركبت الأوتوبيس… راحت عليك",
    flavor: "chocolate",
    theme: "bus",
    length: 3600,
    melt: 0.075,
    sun: 0.5,
    wind: 0,
    dogs: 1,
    kids: 1,
    buses: 2,
    drains: 0,
    fans: 0,
    awnings: 2,
    acs: 0,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 6,
    name: "المول",
    blurb: "التكييف جنّتها — وهي أجرأ",
    flavor: "pistachio",
    theme: "mall",
    length: 3400,
    melt: 0.045,
    sun: 0.1,
    wind: 0,
    dogs: 0,
    kids: 2,
    buses: 0,
    drains: 0,
    fans: 1,
    awnings: 0,
    acs: 4,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 7,
    name: "الشاطئ",
    blurb: "بتذوب أسرع… والنورس جعان",
    flavor: "mango",
    theme: "beach",
    length: 3800,
    melt: 0.125,
    sun: 1,
    wind: 40,
    dogs: 0,
    kids: 1,
    buses: 0,
    drains: 0,
    fans: 0,
    awnings: 3,
    acs: 0,
    seagulls: 2,
    cats: 0,
  },
  {
    id: 8,
    name: "فستان العرس",
    blurb: "اتقسّمت! لحس الاتنين",
    flavor: "strawberry",
    theme: "wedding",
    length: 3600,
    melt: 0.08,
    sun: 0.4,
    wind: 0,
    dogs: 0,
    kids: 2,
    buses: 0,
    drains: 0,
    fans: 0,
    awnings: 2,
    acs: 0,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 9,
    name: "البالوعة",
    blurb: "بلوب — ابتعد عن الفتحات",
    flavor: "pistachio",
    theme: "sewer",
    length: 3600,
    melt: 0.07,
    sun: 0.35,
    wind: 0,
    dogs: 1,
    kids: 0,
    buses: 0,
    drains: 4,
    fans: 0,
    awnings: 1,
    acs: 0,
    seagulls: 0,
    cats: 0,
  },
  {
    id: 10,
    name: "سطح الأتوبيس",
    blurb: "الريح بتخطفها من لسانك",
    flavor: "chocolate",
    theme: "rooftop",
    length: 4000,
    melt: 0.085,
    sun: 0.7,
    wind: 90,
    dogs: 0,
    kids: 1,
    buses: 0,
    drains: 0,
    fans: 2,
    awnings: 2,
    acs: 0,
    seagulls: 1,
    cats: 0,
  },
  {
    id: 11,
    name: "قطط الليل",
    blurb: "الليل أبرد… والقطط أسرع",
    flavor: "strawberry",
    theme: "night",
    length: 4000,
    melt: 0.05,
    sun: 0.05,
    wind: 0,
    dogs: 0,
    kids: 0,
    buses: 1,
    drains: 1,
    fans: 0,
    awnings: 1,
    acs: 0,
    seagulls: 0,
    cats: 3,
  },
  {
    id: 12,
    name: "قرص الشمس",
    blurb: "الشمس نازلة. الظل حياة.",
    flavor: "mango",
    theme: "boss",
    length: 4400,
    melt: 0.11,
    sun: 1,
    wind: 20,
    dogs: 1,
    kids: 1,
    buses: 1,
    drains: 1,
    fans: 1,
    awnings: 4,
    acs: 1,
    seagulls: 1,
    cats: 0,
    boss: true,
  },
];

export const FAIL_LINES: Record<
  import("./types").FailReason,
  string[]
> = {
  melt: ["بقعة على الإسفلت", "كانت آيس كريم… بقت موية", "الشمس كسبت"],
  dog: ["الكلب عيّشك", "لحسة للكلب مش ليك", "هو خلّصها في ثانية"],
  kid: ["الولد سبقك بالملعقة", "يا نهار أسود يا معلّم"],
  drain: ["بلوب", "في المجاري يا معلم", "البالوعة جعانة"],
  bus: ["الميكروباص خدها على كرسي", "اتصدرت من غير تذكرة"],
  seagull: ["النورس مش ناوي يشارك", "طارت في السما"],
  cat: ["القطة لحست وهربت", "مياو… راحت"],
};

export const WIN_LINES = ["في البق!", "لحسة ملوك", "يا حلاوة", "ثبّتوها!"];
