const puzzles={clock:{title:'Seven Chimes',description:'The clock is frozen, but its chimes left a pattern. Which sequence did you hear in the whisper?',type:'options',options:['3 · 6 · 9','7 · 11 · 4','11 · 4 · 7'],answer:2,reward:'Brass cog',icon:'⚙',clue:['THE CLOCKWORK','The chimes hide a sequence: 11, 4, 7.']},painting:{title:"The Lady's Gaze",description:'Follow the direction of the lady’s eyes. What is she watching?',type:'options',options:['The red book','The clock','The main door'],answer:1,reward:'Coded scrap',icon:'▤',clue:['A PAINTED WARNING','The lady is watching the clock, not the door.']},desk:{title:'The Hidden Drawer',description:'A number is repeated throughout the room. Enter the four-digit combination.',type:'code',answer:'1147',reward:'Small key',icon:'⚿',clue:['A FAMILIAR TIME','11:47 is more than a time. It is a key.']}};
const objects={clock:{title:'The Antique Clock',description:'Its hands are frozen at 11:47. Seven faint scratches surround the brass face. Something is hidden behind the dial.',icon:'◷'},painting:{title:"The Lady's Portrait",description:'The varnish is cracked and her eyes seem to follow something in the room. A small symbol is painted into the frame.',icon:'♢'},desk:{title:'The Writing Desk',description:'The top drawer will not open. A thin line of light shines between its panels. There may be a combination hidden nearby.',icon:'▤'},door:{title:'The Main Door',description:'A heavy oak door. The keyhole is cold to the touch. Find the right key and drag it here.',icon:'▣'}};
let solved=JSON.parse(localStorage.getItem('silent-house-solved')||'[]'),current=null,selected=null,zoomKey=null,selectedItem=null,audioCtx=null;
const $=s=>document.querySelector(s);
function sound(kind='click'){if(!audioCtx)return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.value=kind==='success'?660:kind==='wrong'?150:330;g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.18);o.connect(g).connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.2)}
function begin(){audioCtx=new(window.AudioContext||window.webkitAudioContext)();sound();$('#intro').classList.add('hidden');showToast('The house is awake. Find a way out.')}
function enterZoom(key){zoomKey=key;const o=objects[key];$('#zoomTitle').textContent=o.title;$('#zoomDescription').textContent=o.description;$('#zoomObject').textContent=o.icon;$('#inspectBtn').textContent=key==='door'?'THE DOOR IS LOCKED':'EXAMINE OBJECT';$('#zoomView').classList.add('open');sound()}
function leaveZoom(){$('#zoomView').classList.remove('open');zoomKey=null;sound()}
function inspect(){if(!zoomKey)return;if(zoomKey==='door'){showToast('The keyhole is waiting. Drag the Small key here.');return}openPuzzle(zoomKey)}
function openPuzzle(key){current=key;selected=null;const p=puzzles[key];$('#modalTitle').textContent=p.title;$('#modalDescription').textContent=p.description;$('#modalStatus').textContent='';$('#puzzleBody').innerHTML=p.type==='code'?'<input class="code-input" id="codeInput" maxlength="4" inputmode="numeric" placeholder="••••">':`<div class="puzzle-options">${p.options.map((x,i)=>`<button data-i="${i}">${x}</button>`).join('')}</div>`;if(p.type==='options')document.querySelectorAll('.puzzle-options button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.puzzle-options button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');selected=+b.dataset.i;sound()});$('#modal').classList.add('open');sound()}
function closePuzzle(){$('#modal').classList.remove('open')}
function showToast(text){const t=$('#toast');t.textContent=text;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),3000)}
function solve(){const p=puzzles[current],correct=p.type==='code'?$('#codeInput').value===p.answer:selected===p.answer;if(!correct){$('#modalStatus').textContent='Not quite. Look closer.';sound('wrong');return}if(!solved.includes(current)){solved.push(current);localStorage.setItem('silent-house-solved',JSON.stringify(solved));addItem(p);addClue(p.clue);updateProgress()}closePuzzle();leaveZoom();sound('success');showToast(`Item acquired: ${p.reward}`);if(solved.length===3)setTimeout(()=>showToast('The key is ready. Drag it to the main door.'),1700)}
function addItem(p){const slot=[...$('#inventory').children].find(x=>x.classList.contains('empty-slot'));if(slot){slot.className='item';slot.draggable=true;slot.dataset.item=p.reward;slot.innerHTML=`${p.icon}<small>${p.reward}</small>`;slot.onclick=()=>{selectedItem=p.reward;document.querySelectorAll('.item').forEach(x=>x.style.outline='');slot.style.outline='2px solid var(--gold2)';showToast(`${p.reward} selected. Tap the object that needs it.`)};slot.ondragstart=e=>{slot.classList.add('dragging');e.dataTransfer.setData('text/plain',p.reward)};slot.ondragend=()=>slot.classList.remove('dragging')}}
function useItemOnDoor(item){if(item==='Small key'&&solved.includes('desk')){showToast('The key turns. The main door is opening…');sound('success');selectedItem=null;document.querySelectorAll('.item').forEach(x=>x.style.outline='');setTimeout(()=>showToast('A cold corridor waits beyond the library.'),1800);$('#doorState').textContent='OPEN'}else showToast('This tool does not fit the lock.')} 
function addClue(c){const el=document.createElement('div');el.className='clue';el.innerHTML=`<span>◌</span><div><strong>${c[0]}</strong><p>${c[1]}</p><time>JUST NOW</time></div>`;$('#clueList').prepend(el)}
function updateProgress(){const n=solved.length+1;$('#progressText').textContent=`${Math.min(n,4)} OF 4`;$('#progressBar').style.width=`${Math.min(n,4)*25}%`;if(solved.length===3)$('#doorState').textContent='READY'}
function init(){solved.forEach(k=>{addItem(puzzles[k]);addClue(puzzles[k].clue)});updateProgress();$('#startBtn').onclick=begin;document.querySelectorAll('.hotspot').forEach(b=>b.onclick=()=>enterZoom(b.dataset.puzzle));$('#mainDoor').onclick=()=>{if(selectedItem){useItemOnDoor(selectedItem)}else enterZoom('door')};$('#backBtn').onclick=leaveZoom;$('#inspectBtn').onclick=inspect;$('#closeModal').onclick=closePuzzle;$('#solveBtn').onclick=solve;$('#modal').onclick=e=>{if(e.target.id==='modal')closePuzzle()};$('#mainDoor').ondragover=e=>{e.preventDefault();$('#mainDoor').dataset.drop=true};$('#mainDoor').ondragleave=()=>delete $('#mainDoor').dataset.drop;$('#mainDoor').ondrop=e=>{e.preventDefault();delete $('#mainDoor').dataset.drop;const item=e.dataTransfer.getData('text/plain');useItemOnDoor(item)};let hints=3;$('#hintBtn').onclick=()=>{if(!hints){showToast('No hints left. Trust your instincts.');return}const arr=['Listen to the whisper: time begins when music stops.','The painted lady is looking toward the center of the room.','Some numbers appear twice in this room.'];showToast(arr[3-hints]);hints--;$('#hintCount').textContent=`${hints} hints remaining`};$('#soundToggle').onclick=e=>{if(!audioCtx)audioCtx=new(window.AudioContext||window.webkitAudioContext)();e.target.textContent=e.target.textContent==='ON'?'OFF':'ON';showToast(e.target.textContent==='OFF'?'Atmosphere muted.':'Atmosphere enabled.');sound()};$('#journalBtn').onclick=()=>showToast('Your journal is filling with secrets.')}
init();